from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Optional, Any, Dict

try:
    import yaml  # optional (for --to ir --ir-format yaml)
except Exception:
    yaml = None


# ============================================================
# 1) 간단 언어 감지 (rules/actions vs rule/action 만 사용)
# ============================================================

_WORD_RULES = re.compile(r"\brules\b", re.IGNORECASE)
_WORD_ACTIONS = re.compile(r"\bactions\b", re.IGNORECASE)
_WORD_RULE = re.compile(r"\brule\b", re.IGNORECASE)
_WORD_ACTION = re.compile(r"\baction\b", re.IGNORECASE)

def detect_lang_from_ow_minimal(ow_text: str) -> tuple[str, float, dict]:
    """
    'rules actions' vs 'rule action' 두 패턴만으로 언어 판정.
    반환: (lang, confidence, details)
      - lang: "en" 또는 "ko"
      - confidence: 0.0 ~ 1.0 단순 점수
      - details: 디버깅용 카운트
    정책(임시):
      - (rules+actions) > (rule+action) -> "en"
      - (rule+action) > (rules+actions) -> "ko"
      - 동률이면 "en"
    """
    plural_count = len(_WORD_RULES.findall(ow_text)) + len(_WORD_ACTIONS.findall(ow_text))
    singular_count = len(_WORD_RULE.findall(ow_text)) + len(_WORD_ACTION.findall(ow_text))

    if plural_count > singular_count:
        lang = "en"
    elif singular_count > plural_count:
        lang = "ko"
    else:
        lang = "en"  # tie-breaker

    total = plural_count + singular_count
    confidence = (abs(plural_count - singular_count) / total) if total > 0 else 0.3

    details = {
        "plural_rules": len(_WORD_RULES.findall(ow_text)),
        "plural_actions": len(_WORD_ACTIONS.findall(ow_text)),
        "singular_rule": len(_WORD_RULE.findall(ow_text)),
        "singular_action": len(_WORD_ACTION.findall(ow_text)),
    }
    return lang, min(0.95, 0.5 + confidence / 2), details


# ============================================================
# 2) 간단한 디컴파일 코어 (스켈레톤)
# ============================================================

def to_python(
    ow_text: str,
    *,
    lang: str = "en",
    strict: bool = False,
    preserve_identifiers: bool = False,
) -> str:
    """
    OW 텍스트를 Python DSL로 변환 (스켈레톤).
    실제 파싱/재구성 로직은 TODO.
    """
    header = [
        "# Generated by flowover (OW -> Python DSL)",
        f"# lang={lang} strict={strict} preserve_identifiers={preserve_identifiers}",
        "",
        "from src.DSL.overwatch import *  # TODO: adjust import path",
        "",
        "# TODO: decompiled rules below",
        "def main():",
        "    pass",
        "",
        "if __name__ == '__main__':",
        "    main()",
        "",
    ]
    return "\n".join(header)


def to_ir(
    ow_text: str,
    *,
    lang: str = "en",
    strict: bool = False,
) -> Dict[str, Any]:
    """
    OW 텍스트를 IR(JSON/YAML)로 변환 (스켈레톤).
    실제 파싱/IR 구성은 TODO.
    """
    return {
        "version": 1,
        "lang": lang,
        "strict": strict,
        "units": [
            {
                "kind": "rule",
                "name": "TODO_rule_name",
                "conditions": [],
                "actions": [],
                "source_range": None,
            }
        ],
        "diagnostics": [],
        "meta": {
            "generator": "flowover",
            "format": "pyoverflow-ir",
        },
    }


# ============================================================
# 3) 보조 유틸 (config 언어 읽기 등)
# ============================================================

def _read_lang_config(config_path: Path) -> str:
    if config_path.exists():
        try:
            with config_path.open("r", encoding="utf-8") as f:
                if yaml is not None:
                    cfg = yaml.safe_load(f) or {}
                    return cfg.get("language", "en")
        except Exception:
            pass
    return "en"


def _decide_output_path(
    src_path: Path, output_arg: Optional[str], to: str, ir_format: str
) -> Optional[Path]:
    """
    출력 경로 결정:
      - output_arg == "-" -> stdout(None 반환)
      - 미지정 시 모드별 디폴트 확장자
    """
    if output_arg == "-":
        return None  # stdout
    if output_arg:
        return Path(output_arg).resolve()

    if to == "py":
        return src_path.with_suffix(".py")
    if to == "ir":
        return src_path.with_suffix(".ir.yaml" if ir_format == "yaml" else ".ir.json")
    return src_path.with_suffix(".out")


def _write_text(out_path: Optional[Path], text: str, *, force: bool, prog: str) -> int:
    """
    파일/표준출력 쓰기. 0 또는 3 반환.
    """
    if out_path is None:
        sys.stdout.write(text)
        if not text.endswith("\n"):
            sys.stdout.write("\n")
        return 0

    if out_path.exists() and not force:
        ans = input(
            f"[{prog}] warning: '{out_path}' already exists. Overwrite? (Y/n): "
        ).strip().lower()
        if ans not in ("y", "yes", ""):
            print(f"[{prog}] cancelled by user.")
            return 0

    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8", newline="\n")
        print(f"[{prog}] Wrote: {out_path}")
        return 0
    except Exception as e:
        print(f"[{prog}] error: failed to write output: {e}", file=sys.stderr)
        return 3


# ============================================================
# 4) CLI 엔트리포인트
# ============================================================

def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="flowover",
        description="flowover — Decompile Overwatch Workshop → Python DSL or IR",
    )
    parser.add_argument(
        "src",
        help="Source OW file path (e.g., rules.ow) or '-' to read from stdin",
    )
    parser.add_argument(
        "--to",
        choices=["py", "ir"],
        default="py",
        help="Decompile target: Python DSL ('py') or IR ('ir')",
    )
    parser.add_argument(
        "--ir-format",
        choices=["json", "yaml"],
        default="json",
        help="IR output format (effective only when --to=ir)",
    )
    parser.add_argument(
        "-o", "--output",
        default=None,
        help="Output file path (use '-' for stdout). Default: deduced from input",
    )
    parser.add_argument(
        "-f", "--force",
        action="store_true",
        help="Overwrite output without asking",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail on unknown/unsupported tokens instead of stubbing them",
    )
    parser.add_argument(
        "--preserve-identifiers",
        action="store_true",
        help="Attempt to preserve original identifiers/labels in decompiled output",
    )
    # 고정 정책: lang 자동 감지는 rules/actions vs rule/action만으로 수행
    # (--lang 옵션은 의도적으로 제거)

    args = parser.parse_args(argv)

    # -------- 입력 읽기 --------
    if args.src == "-":
        try:
            ow_text = sys.stdin.read()
            src_path = Path("stdin.ow")
        except Exception as e:
            print(f"[flowover] error: failed to read stdin: {e}", file=sys.stderr)
            return 1
    else:
        src_path = Path(args.src).resolve()
        if not src_path.exists():
            print(f"[flowover] error: source not found: {src_path}", file=sys.stderr)
            return 1
        if not src_path.is_file():
            print(f"[flowover] error: not a file: {src_path}", file=sys.stderr)
            return 1
        try:
            ow_text = src_path.read_text(encoding="utf-8")
        except Exception as e:
            print(f"[flowover] error: failed to read source: {e}", file=sys.stderr)
            return 1

    # -------- 언어 감지 (minimal) --------
    auto_lang, conf, details = detect_lang_from_ow_minimal(ow_text)
    print(f"[flowover] Language auto-detected (minimal): {auto_lang} "
          f"(confidence={conf:.2f}, counts={details})")

    # -------- 디컴파일 --------
    try:
        if args.to == "py":
            py_text = to_python(
                ow_text,
                lang=auto_lang,
                strict=args.strict,
                preserve_identifiers=args.preserve_identifiers,
            )
            out_path = _decide_output_path(src_path, args.output, to="py", ir_format=args.ir_format)
            return _write_text(out_path, py_text, force=args.force, prog="flowover")
        else:
            ir_obj = to_ir(ow_text, lang=auto_lang, strict=args.strict)
            if args.ir_format == "yaml":
                if yaml is None:
                    print(
                        "[flowover] error: PyYAML is required for --ir-format yaml",
                        file=sys.stderr,
                    )
                    return 2
                text = yaml.safe_dump(ir_obj, allow_unicode=True, sort_keys=False)
            else:
                text = json.dumps(ir_obj, ensure_ascii=False, indent=2)
            out_path = _decide_output_path(src_path, args.output, to="ir", ir_format=args.ir_format)
            return _write_text(out_path, text, force=args.force, prog="flowover")

    except Exception as e:
        print(f"[flowover] error: decompilation failed: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
